[app]
remoteAddr = "10.90.44.73"
remotePort = "2000"
usingNC = true #  是否使用NC反弹shell
usingSH = false # true:sh or false:bash
test = true #  是否测试模式

[app.schedule]
userName = "futx" # 调度系统使用的用户名

[app.scpInfo]
root = "/home/realestate_test/futh/dist/sbin/cal" #  脚本的根路径
dataSync = "flow-data-sync"
gpsConfigure = "flow-gps-pre"
batchDaily = "flow-batch1-daily"
batchResult = "flow-batch2-result"
batchPy = "flow-batch3-py"
month = "flow-batch-mon"

[app.bus]

[[app.bus.portrait]]
name = "上传"
type = 0

[[app.bus.portrait]]
name = "媒介"
type = 1

[[app.bus.portrait]]
name = "客群来源去向"
type = 2

[[app.bus.portrait]]
name = "客群来源去向"
type = 3

[[app.bus.portrait]]
name = "全国客流"
type = 4

[[app.bus.portrait]]
name = "基础画像"
type = 5

[[app.bus.portrait]]
name = "thermalchartofsourceflow"
type = 6

[[app.bus.portrait]]
name = "周边"
type = 7

[app.db]
userName = "root"
password="*****"
url = "*******"
port = 3306
storeHouse = "***"
type = "mysql"

[[queue]]
queueName = "root.app"

[[queue]]
queueName = "root.app2"

