name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-18.04
    container: centos:7

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        
    - name: configure
      run: chmod +x ./configure && ./configure
      
    - name: Install world
      run: make
